# Generated by Django 5.1.2 on 2024-10-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
